version: '3.7'
services:
  ui:
    build:
      context: ./ui/
      args:
        UID: ${VUID}
        GID: ${VGID}
    user: "${VUID}:${VGID}"
    volumes:
      - ./ui:/usr/src/app
    working_dir: /usr/src/app
    command: yarn dev
    tty: true
    ports:
      - 8010:3000
    environment:
      API_BASE_URL: http://localhost:8011
  api:
    build:
      context: ./api
    user: "${VUID}:${VGID}"
    volumes:
      - ./api:/usr/src/app
    environment:
      DB_URL: ${DB_URL}
      FLASK_ENV: development
      UI_BASE_URL: http://localhost:8010
    ports:
      - 8011:8000
    depends_on:
      - db
  db:
    image: postgres:12.3-alpine
    ports:
      - 25432:5432
    volumes:
      - ./db/init.d:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: db

networks:
  default:
    driver: bridge
